package main

import (
	"fmt"
	"music-library/config"
	"music-library/database"
	"music-library/handlers"
	"music-library/models"
	"os"

	"github.com/gin-gonic/gin"                 // swagger embed files
	swaggerFiles "github.com/swaggo/files"     // импорт swagger файлов
	ginSwagger "github.com/swaggo/gin-swagger" // gin-swagger middleware

	_ "music-library/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Music Library API
// @version 1.0
// @description This is a simple music library API.
// @host localhost:8080
// @BasePath /

func main() {
	// Загрузка конфигураций из .env файла
	config.LoadEnv()

	// Подключение к базе данных
	database.ConnectDB() // Просто вызываем функцию подключения без присвоения

	// Авто-миграция моделей
	db := database.GetDB() // Получаем экземпляр базы данных
	db.AutoMigrate(&models.Song{})

	// Инициализация роутера
	r := gin.Default()

	// Регистрация маршрутов
	handlers.RegisterRoutes(r)

	// Swagger
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler)) // Используем swaggerFiles.Handler

	// Запуск сервера
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}
	r.Run(fmt.Sprintf(":%s", port))
}
